import { Text } from '@chakra-ui/react';
import Head from 'next/head';
import { Header } from "../components/Header";

export default function Home() {
    return (
        <>
            <Head>
                <title>WORLD TRIP | HOME</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main >
                <Header />
                <Text>Main nova</Text>
            </main>
        </>
    )
}
