import { Banner } from '@/components/Banner';
import { SlidesConteiner } from '@/components/Slides';
import { TravelsTypes } from '@/components/TravelsType';
import { getPrismicClient } from '@/services/prismic';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import { Header } from "../components/Header";
import { useEffect } from 'react';
import { useContinents } from '@/contexts/continentsContexts';
import { continentObjectFormarter } from '@/utils/functions';
import { HomeProps } from '@/interface/homeInterface';


export default function Home({ continentsAll }: HomeProps) {
    const { setContinents } = useContinents();
    useEffect(() => {
        if (continentsAll) {
            setContinents(continentsAll)
        }
    }, [continentsAll, setContinents])
    return (
        <>
            <Head>
                <title>WORLD TRIP | HOME</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main >
                <Header />
                <Banner />
                <TravelsTypes />
                <SlidesConteiner />
            </main>
        </>
    )
}


export const getStaticProps: GetStaticProps = async ({ }) => {
    const prismic = getPrismicClient({})
    const continents = await prismic.getAllByType("continent", {
        orderings: {
            field: 'document.first_publication_date',
            direction: 'asc',
        }
    });

    const continentsFormart = continents.map((continent) => {
        return continentObjectFormarter(continent)
    });

    return {
        props: { continentsAll: continentsFormart },
        revalidate: 60 * 60 * 24 // 24 Horas
    }
}